language: node_js
node_js:
- '0.10'
before_script:
- gem update --system
- gem install sass
- gem install compass
env:
  global:
  - secure: BnZaphWMP4nNVhYa8e40fPtRKoWUh+ScuCCpVy63wYfp2EM9+P+UYGwATgr8SOdHECCNxwrKL0m3excw85JlpCwiAWoVJwUjA48ytavDM/2NvdjZ6QYdNSvLSg0mF5OzX8Rtzjf06l6B+zuXwguFbuaCl6epGEx6gMdzL6nAwRc=
  - secure: mA/tvHfWb/KyQLHRDeY261DzyJcx8b+o5Esbcvn1AxC6Tc5RpF9Jmn8NrVSslqkF7IHY3gFIGJ2cuXXpk80diIYauUlnJDCDRP8nI6Dnkh09anmErcAI6jDIxhT+FBW+63LLGJEwwjsKdaDvU65Dt6zMVznrPYzRFMtTj+njhqM=
addons:
  sauce_connect: true
